source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
target 'BaseNavForm' do
pod 'AFNetworking','~> 3.2.0'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'JPush', '~> 3.0.8'
pod 'Masonry', '~> 1.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'SDWebImage', '~> 4.4.0'
pod 'AVOSCloud', '~> 11.0.0'
pod 'CocoaSecurity', '~> 1.2.4'
pod 'Toast', '~> 4.0.0'
pod 'NJKWebViewProgress'
end

